blank_issues_enabled: false
contact_links:
  - name: webforJ Documentation
    url: https://docs.webforj.com/
    about: Learn more about webforJ
  - name: Contact Us
    url: https://webforj.com/schedule-discovery/
    about: Interested in webforJ? Book a short meeting, you'll discover what webforJ is, and we'll discuss how it can best meet your needs in preparation for a robust demonstration.

